### ISSUE TITLE
How to use when On/Off sends different code

### ISSUE THREAD

**Issue by RanaInside** [cgrossde/RPi.RCSwitchWebapp#1]
code is based on an assumption that there is one system code, and each switch has a numeric id that can be toggled with 1 or 0

with my EnerGenie outlets, when pressing On for Channel 1, I get the code 8782927; pressing off I get 8782926

I'm using 433Utils codesend and sniffer to get my code.

**Comment by cgrossde** [comment]
Just adapt [switchcontrol.php](https://github.com/cgrossde/RPi.RCSwitchWebapp/blob/master/switchcontrol.php) accordingly.
